msdio/Tamago

client/.storybook/main.js, client/.storybook/preview.js, client/package.json, client/src/pages/_app.tsx, client/src/pages/index.tsx, client/tsconfig.json, client/yarn.lock
close #1 
프론트 프로젝트 초기 세팅이 완료되었습니다!
next.js 환경을 커스텀으로 세팅하였습니다.
[참고한 블로그](https://velog.io/@msdio/next-%ED%99%98%EA%B2%BD-%EC%B2%98%EC%9D%8C%EB%B6%80%ED%84%B0-%EC%84%B8%ED%8C%85%ED%95%98%EA%B8%B0)
node version : `16.17.0`
package manager : `yarn`
- next, react, react-dom
- typescript, @types
- eslint, prettier
- emotion, chakra-ui
- storybook, jest
자세한 사항은 [노션 링크](https://www.notion.so/0e139fdbbfc24dff8e8d0309d9f82a06)에서 참고하시면 됩니다.
=> 프론트엔드 프로젝트 세팅

backend/src/test/java/com/project/Tamago/TamagoApplicationTests.java
=> fix : build 오류를 피하기 위한 테스트 코드 주석화

dockerfile/backend/Dockerfile, dockerfile/backend/application-secret.yml, dockerfile/backend/backend_install.sh, dockerfile/backend/window_backend_run_with_gitbash.sh
-  backend dockerfile 생성 
-  local에서 쉽게 실행할 수 있도록 .sh 명령어 추가
- X
-   가장 빨리 만나는 도커 책, 너무 많은 웹사이트 참조..
=> feat: backend dockerfile 생성 및 local에서 쉽게 실행할 수 있도록 .sh 명령어 추가

.github/workflows/backend-ci.yml, .github/workflows/backend-deploy.yml, dockerfile/backend/delete_not_use_image_file.sh
- Github action CI/CD 파이프라인 구축
-  깃허브 파이프라인 추가
=> Github action CI/CD 파이프라인 구축

.github/workflows/backend-ci.yml, backend/src/main/java/com/project/Tamago/domain/Typing.java
=> [#44] fix: fix backend-ci.yml

backend/src/main/java/com/project/Tamago/domain/Typing.java
=> [#44] fix: github action파이프라인 확인

backend/src/main/java/com/project/Tamago/domain/Typing.java
=> [#44] fix: github action파이프라인 확인 Revert

client/build-storybook.log, client/package.json, client/src/styles/theme.ts, client/yarn.lock
close #26 
스토리북을 배포하기 위한 세팅을 진행하였습니다.
스토리북의 정적 배포에는 [chromatic](https://www.chromatic.com/)을 사용했습니다.
chromatic을 선택한 이유는 아래와 같습니다.
- storybook의 maintainer 들이 만든 무료 배포 서비스이므로, storybook 배포 관련 편의성을 많이 제공합니다.
- 공식 홈페이지에서도 chromatic을 사용한 배포를 권장하고 있으며, 자세한 가이드 또한 제공하고 있습니다.
- 스토리북 배포를 진행하기 위해 프로젝트에 chromatic을 설치했습니다.
- 또한 main에 push 할 경우, github actions를 통해 자동으로 스토리북 배포가 진행되도록 설정했습니다.
- 혹시 키 값이 노출된걸 발견하신다면... 제보 부탁드립니다...
-   [Deploy Storybook (official website)](https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/)
=> [#26] 스토리북을 배포했습니다.

.github/workflows/chromatic.yml
=> [#26] release: storybook 배포 자동화

client/package.json
=> [#26] release: storybook 배포 자동화 테스트

dockerfile/backend/Dockerfile, dockerfile/backend/backend_install.sh, dockerfile/backend/delete_not_use_image_file.sh
- 도커 파일에서 test 검증부분 제거
- git install 부분을 이미지로 받아오도록 변경
=> [#44] Feature/backend/docker file

dockerfile/backend/Dockerfile, dockerfile/backend/backend_install.sh, dockerfile/backend/delete_not_use_image_file.sh
- 도커 파일 변경. 백엔드 배포 파이프라인 설정 완료!
=> [#44] 도커 파일 내용 변경, 백엔드 배포 파이프라인 설정 완료

client/build-storybook.log, client/src/components/footer/index.stories.tsx, client/src/components/login/LoginForm/index.stories.tsx, client/src/components/signup/Form/index.stories.tsx, client/src/components/signup/Form/index.tsx
스토리 파일들을 추가했습니다.
새로운 스토리들의 배포도 완료되었습니다.
=> [#26] footer, loginform, signup form 의 스토리를 추가했습니다.

backend/src/main/java/com/project/Tamago/controller/AuthController.java
=> [refactor] 쓰지않는 파라미터값 제거

client/package.json, client/src/apis/auth.ts, client/src/apis/index.ts, client/yarn.lock
client api 초기 세팅
- axios pakage install
- axios instance 생성
- .env 파일 생성 (backend server url)
- api 초기 구조 설계
- 기존에 사용하시던 파일 명이나, 생성방식, 구조가 있다면 말씀해주세요!
=> [#80] Front API 초기 세팅

.github/workflows/backend-deploy-local.yml, dockerfile/backend-run.sh, dockerfile/backend/Dockerfile-Local
- backend 로컬 도커 이미지 파이프라인 설정
- backend 로컬 도커 이미지 파이프라인 설정
=> [#79] feat : local backend docker image build

backend/.gitignore
=> [#79] 파이프라인 테스트

.github/workflows/frontend-ci.yml, .github/workflows/frontend-deploy.yml, client/package.json, client/src/apis/auth.ts, client/src/components/common/FormOr/index.stories.tsx, client/src/components/footer/index.stories.tsx, client/src/components/header/index.tsx, client/src/components/login/Form/index.tsx, client/src/components/signup/Form/index.tsx, client/src/components/signup/Terms/IconCheckbox.tsx, client/src/components/signup/Terms/index.tsx, client/src/hooks/useRegexInputs.ts, client/src/utils/test/path.test.js
프론트엔드 파이프라인을 구축했습니다.
Next.js - Github Actions - AWS S3 를 연결했습니다.
- 빌드 시에 오류를 해결하기 위해 타입 터지고 린트 터지는 기존 코드들을 많이 주석처리 했습니다. 나중에 확인해야 할 것 같아요. 기능이 갑자기 안될 수 있습니다!
-
-
-   [링크 이름](링크 주소)
-
=> [#67] 프론트엔드 github actions 파이프라인 구축

dockerfile/backend-run-window.sh
=> fix: 오타 수정

dockerfile/backend-run-window.sh, dockerfile/backend-run.sh, dockerfile/readme.md
- backend-run.sh 사용법 readme에 추가
- backend-run.sh 사용법 readme에 추가 
- **H2 console** 사용 시 유의사항을 꼭 읽어주세요!
=> [document] backend-run.sh 사용법 readme에 추가

dockerfile/backend/delete_not_use_image_file.sh
- 필요없는 도커 이미지 제거하는 shell scripte 변경
- 필요없는 도커 이미지 제거하는 shell scripte 변경
=> fix : delete image file change

backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
=> [fix] 테스트코드만 작성한 부분 Disabled

backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
- 테스트 실패 상황 원인 파악 및 변경
- assert를 equal하는 부분은 contains로 변경
=> [Test] test code 오류 상황 변경

backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java, backend/src/main/java/com/project/Tamago/controller/AuthController.java, backend/src/main/java/com/project/Tamago/controller/UserController.java, backend/src/main/java/com/project/Tamago/dto/CustomResponse.java, backend/src/main/java/com/project/Tamago/dto/SuccessMessage.java
- 기존에 반환값이 void인 함수들의 경우 응답을 successmessage로 나머지는 customreponse로 하고있었던걸 customresponse로 통일했습니다
=> successMessage삭제 customResponse 적용

.github/workflows/backend-ci.yml
=> fix: 백엔드 CI 변경

backend/src/main/java/com/project/Tamago/controller/TypingController.java, backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java, backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
short 글에 CustomResponse 추가
- short Typing 부분도 이제 Code와 Description도 추가돼서 내용이 전달됩니다
=> [refactor] short 글에 CustomResponse 추가

backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java, backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
- controlleradvice에 이메일과 비번이 틀렸을때의 오류를 캐치해 응답하도록 했습니다
=> 로그인시 유효성 검증

README.md
리드미 초안 작성
- 리드미 초안 작성
- 이름 순서는 msdio - sumi - yunu - jhbaik - tkddls 순으로 작성했습니다. 바꾸고 싶으면 알려주세요!
=> [#137] feat: 리드미 초안 작성

.github/workflows/frontend-ci.yml
=> speed up CI pipeline

client/src/styles/font.css
- close #201 
- d2 coding css 주소 변경
-
-
-
-
-   [링크 이름](링크 주소)
-
=> d2 coding 배포시 콘솔 오류

client/src/styles/font.css
=> font import 주소 변경

.github/workflows/frontend-deploy.yml, client/src/apis/typing.ts
- github action 문법을 잘못 쓰고 있어서 수정
- long typing 쪽 api에서 baseurl을 2번 호출하는 코드 수정
-
-
-
-
-   [링크 이름](링크 주소)
-
=> 깃허브 액션 잘못된 문법, api 요청 주소 수정

client/src/apis/auth.ts, client/src/apis/index.ts
api interceptor를 수정하고, 익명 함수 선언식을 화살표 함수로 변경했습니다.
- api interceptor를 일관된 형식으로 변경했습니다.
- api 설정 부분의 함수 선언식을 화살표 함수로 변경했습니다.
-
-
-   [화살표 함수에 대한 discussion](https://github.com/msdio/Tamago/discussions/199#discussioncomment-5393157)
-
=> api interceptor 수정 및 arrow function으로 변경

client/src/apis/auth.ts, client/src/apis/index.ts, client/src/components/header/index.tsx, client/src/components/login/index.tsx, client/src/components/signup/Form/index.tsx
close #195 
로그인 기능까지 복구됐습니다.
로그인 후 메인에 오면 회원가입 / 로그인 버튼이 있던 곳에 유저 정보가 떠야 하는데, API가 업데이트 된 이후로 해당 화면은 업데이트 하겠습니다.
- api 쪽을 다듬었습니다. 이제 apis > auth.ts 파일은 일관된 형식으로 변경됐습니다.
-
-
-   [api 관련된 discussion](https://github.com/msdio/Tamago/discussions/199)
-
=> [#195] 로그인 기능이 복구됐습니다.

client/src/utils/test/char.test.ts
=> fix: api base url 수정

backend/src/main/java/com/project/Tamago/config/CorsConfig.java
swagger에서 cors에러가 생기는 문제 해결
- swagger에서 cors에러가 생기는 문제 해결
=> [bugfix] swagger에서 cors에러가 생기는 문제 해결

client/.eslintrc.json, client/src/apis/auth.ts, client/src/apis/index.ts, client/src/apis/typing.ts, client/src/components/common/Confirm/index.tsx, client/src/components/common/ResultModal/practice-mode.tsx, client/src/components/practice/short/CurrentTyping/index.tsx, client/src/components/practice/short/InfoBar/index.tsx, client/src/components/practice/short/OriginalTyping/index.tsx, client/src/components/practice/short/_hook/contextShortTyping.tsx, client/src/components/practice/short/_hook/useCurrentTyping.ts, client/src/components/practice/short/index.tsx, client/src/hooks/useToggle.ts, client/src/types/typing.ts, client/src/utils/typing.ts
아직 구현중입니다!
- access token 저장 버그 수정
- 짧은 타이핑 자잘한 버그 수정
- interface에 있는 변수 no-unused-vars error 뜨는거 해결
- 연습모드 모달 구현
- 짧은 글 타이핑 히스토리 저장 API 연결
- access token 저장이 잘못되고 있어 수정했습니다
- useToggle hook을 만들었어요! discussions 한번 확인 부탁드립니다.
- @coolsmart2 연습모드 모달 props 한번 확인 부탁드립니다!
=> 짧은글 타이핑 게임 

client/src/styles/theme.ts, client/src/styles/typo.ts
폰트 디자인 시스템 적용 완료
- `styles > typo.ts` 파일입니다.
- 사용법은 아래와 같습니다.
```tsx
<Text textStyle='point/hd1'></Text>
```
위처럼 피그마와 동일하게 사용 가능합니다.
=> [#241] 폰트 디자인 시스템

client/src/components/home/Banner/index.tsx, client/src/components/home/Landing/index.tsx, client/src/components/home/Menus/index.tsx
수민님 피드백에 따라 몇 가지 변경사항을 반영했습니다.
- `About Tamago` 문구와 `이제는 개발에 재미를 더해요` 문구에 margin-left 값을 추가했습니다.
- 메인화면의 '연습하기' 버튼에 클릭 이벤트가 추가됐습니다.
=> 메인 화면에 수민님 변경사항 반영

client/src/apis/typing.ts, client/src/components/header/DropDown/index.tsx, client/src/components/home/Menus/index.tsx, client/src/components/register/Layout/index.tsx, client/src/components/register/Long/index.tsx, client/src/pages/register.tsx
백엔드의 요청이 있어 긴 글 등록 기능을 추가했습니다.
- 제목, 내용, 글 종류를 선택할 수 있습니다.
- 아직 validation은 하나도 안돼있어요! 우선 급하게 필요해서 만든거라 다음주 중으로 코드 정리랑 프론트에서의 validation을 추가할 예정입니다.
-
-
-   [링크 이름](링크 주소)
-
=> 긴 글 등록 기능 추가

client/src/components/typing/long/List/TypingListPagination/index.tsx, client/src/constants/typing.ts, client/src/pages/practice/long/index.tsx
=> 긴 글 리스트 페이지네이션 버그 해결 + 긴 글 리스트 타입 추가

client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
글 선택 화면 모달 가려지는 문제 수정
- z-index 추가
-
=> 글 선택 화면 모달 가려지는 문제 수정

client/src/components/home/Stats/index.tsx, client/src/pages/404.tsx
#260 에 남아있는 버그들을 모두 수정했습니다.
- 메인화면에서 통계 클릭 시 준비중인 기능이라는 alert를 띄워줍니다.
- 404 페이지에서 이전 페이지로 가는 버튼의 색상을 변경했습니다.
=> [#260] 메인화면 stat 버튼 클릭 시 alert, outline 색상 오류 수정

client/src/components/typing/long/Exam/index.tsx
=> fix: component error on typing/long/Exam

backend/src/main/java/com/project/Tamago/security/oauth2/OAuth2AuthenticationSuccessHandler.java
- oauth2 리다이렉션 방식으로 변경
- oauth2 리다이렉션 방식으로 변경
=> fix : oauth2 redirection 방식으로 변경

backend/src/main/java/com/project/Tamago/security/oauth2/OAuth2AuthenticationSuccessHandler.java, backend/src/main/java/com/project/Tamago/security/oauth2/OAuthAttributes.java
- redirection 시 userId 값 추가로 보내줌 (https://typingmastergo.site/kakao-redirect?token=토큰값&userId=8)
- jwt 내부 값 변경
=> fix: redirection 시 userId 값 추가로 보내주고, jwt 내부 값 변경

client/src/apis/auth.ts, client/src/components/header/DropDown/index.tsx, client/src/components/login/Form/index.tsx, client/src/constants/paths.ts
라우팅 관련 에러를 수정했습니다.
- 다른 화면에서 글 등록 페이지로 이동할 때에 상대 경로로 이동하고 있어서, 절대 경로로 변경했습니다.
- 카카오 로그인 관련해서 환경 변수 값을 변경하려고 했지만, 수정된 형태가 기존 방식과 일관된 방식인 걸로 판단해 변경했습니다.
=> 라우팅 관련 에러 수정

backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
- 기존 비밀번호 유효성검사 부분에 따진 예외처리 추
- 대소문자특수문자('/' 띄어쓰기 등 제외) 최소 8자이상으로 처리
=> 비밀번호 유효성 검사 수정

client/src/utils/regex.ts
비밀번호 정규식 변경
- `return /v2` 와 같은 경우에 패스워드로 통과가 돼서 정규식을 수정했습니다.
=> 비밀번호 정규식 변경

backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
=> fix: 유효성 검증 정규식 변경에 따른 테스트

backend/src/main/java/com/project/tamago/configuration/config/SwaggerConfig.java
=> swagger 연결 디렉토리 명 변경

dockerfile/backend/Dockerfile
=> fix: dockerfile jar file name change
